[package]
name = "bin"
default-run = "bin"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
app = { path = "../app" }
kernel = { path = "../kernel" }
database = { path = "../database" }

axum = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "parking_lot", "signal"] }
tower-http = { workspace = true, features = ["cors", "fs", "compression-gzip"] }  #compression-gzip
chrono = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "local-time"] }
